baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = '首页'
pageRef = '/'
weight = 10

[services]
  [services.googleAnalytics]
    id = 'G-XXXXXXXXX'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
